version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      #- ./phpmailer:/var/www/phpmailer
